version: '3.7'
services:
  simple-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.1.8-apache
    ports:
      - 18080:80
    volumes:
      - ./htdocs:/var/www/html
    environment:
      PHP_EXTENSION_XDEBUG: 1